# Generated by Django 5.2.6 on 2025-09-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', to='roles.rol'),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
