# Generated by Django 5.2.6 on 2025-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_permiso_nombre'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='color',
            field=models.CharField(default='#444c8a', max_length=7),
        ),
        migrations.AddField(
            model_name='rol',
            name='icono_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='permisos.permiso'),
        ),
    ]
